# Generated by Django 5.0.1 on 2024-01-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workbooks.workbook')),
            ],
        ),
    ]
